[project]
name = "jump-core"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "<3.13, >3.11"
dependencies = [
    "aliby",
    "cellpose>=4.0.7",
    "duckdb>=1.4.2",
    "imagecodecs>=2025.8.2",
    "jump-portrait>=0.0.29",
    "lpips>=0.1.4",
    "matplotlib>=3.0.0",
    "numpy>=1.24.0",
    "pandas>=2.0.0",
    "pillow>=9.0.0",
    "pooch>=1.8.2",
    "polars>=0.19.0",
    "scikit-image>=0.20.0",
    "tqdm>=4.0.0",
    "zarr>=3.1.3",
    "numcodecs>=0.16.5",
    "nahual",
    "jupytext>=1.19.1",
    "cp-measure",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "jupytext>=1.19.1",
    "ruff>=0.14.6",
]

[tool.uv.sources]
aliby = { path = "../aliby" , editable=true}
nahual = { path = "../nahual", editable = true }
cp-measure = { path = "../cp_measure", editable = true }


