
#+OPTIONS: ^:nil
Tables to export to LaTeX with ease

* Tile size and channels
|-----------------+-----------+------------------------+------------------------|
| Model           | Tile size | Channels               | Preprocessing          |
|-----------------+-----------+------------------------+------------------------|
| cp_measure      |        NA | Nuclei,AGP,Mito,RNA,ER | minmax, 0-1            |
| dinov2_random |       224 | Nuclei,AGP,Mito        | standard               |
| morphem         |       224 | Nuclei,AGP,Mito,RNA,ER | standard               |
| openphenom      |       256 | Nuclei,AGP,Mito,RNA,ER | standard, minmax, 8bit |
| subcell         |       448 | Nuclei,AGP,Mito,RNA    | standard               |
# | DINOv2          |       490 | Nuclei,AGP,Mito        | standard               |


* Processing times
** Whole experiment
Note that this only takes the first and last parquet files for each directory. Also we may have used a different number of instances when running the models.
#+begin_src sh :eval no-export :exports results
  ls -lU --time-style=+%s /work/datasets/aliby_output/*/jump_core_annotated/jpegxl_lossy_mq.zarr/profiles |
    awk -f /home/amunoz/projects/JUMP_lite/draft/benchmark_time_ls.awk
#+end_src

#+RESULTS:
| *Model*         | *images/min* | *Hours(total)* | *#images* |
| openphenom    |    1625.41 |      7.45167 |  726720 |
| subcell       |    1766.38 |      6.85694 |  726720 |
| morphem       |    2871.65 |      4.21778 |  726720 |
| dinov2_random |    2406.49 |      5.03306 |  726720 |

** Four plates
This is a more reliable source of ground truth. Each model was instatiated only once.
#+begin_src sh :eval no-export :exports results
  export LC_COLLATE=C
  ls -l --time-style=+%s /work/datasets/aliby_output/*/jump_target2_4plate/jpegxl_lossy_effort_3.zarr/profiles |
    awk -f benchmark_time.awk | xargs -I {} $(head -n 2)
#+end_src

#+RESULTS:
| *Model*         | *Images/min* | *Hours(total)* | *#images* |
| cp_measure    |   0.109853 |      1398.23 |    9216 |
| dinov2_random |    205.409 |     0.747778 |    9216 |
| morphem       |    148.805 |      1.03222 |    9216 |
| openphenom    |    261.323 |     0.587778 |    9216 |
| subcell       |    65.1999 |      2.35583 |    9216 |

We had to fix the fact that half of cp_measure files were processed days before
#+begin_src sh :eval no-export :exports results  
  export LC_COLLATE=C
  find /work/datasets/aliby_output/*/jump_target2_4plate/zstd.zarr/profiles/  -type f -newermt "2025-12-01 0:00:00
  " -printf "%p %T@\n" | awk -f benchmark_time_find.awk | sort
    
#+end_src

#+RESULTS:
| Model         | Images/min | Hours(total) | #images |
| openphenom    |      379.2 |          0.4 |    9216 |
| subcell       |      270.8 |          0.6 |    9216 |
| cp_measure    |        1.3 |         53.7 |    4212 |
| morphem       |      218.4 |          0.7 |    9216 |
| dinov2_random |      284.6 |          0.5 |    9216 |

** Which features are more variable?

Calculate statistics on all features, to validate that the features that drag down feature correlations are basically random noise.
#+begin_src sql
    CREATE TABLE IF NOT EXISTS pivoted AS UNPIVOT(SELECT COLUMNS(lambda x: NOT x.starts_with('Metadata')) FROM read_parquet('/work/users/amunoz/projects/JUMP_core/data/cp_measure_jump_target2_4plate_zstd_raw_features.parquet') ON COLUMNS(*);
  
    COPY (SELECT *, avg/std AS ratio FROM (SELECT feature, MEAN(value) AS avg, stddev_pop(value) as std, var_pop(value) AS var FROM (SELECT split_part(name, '/', 3) AS feature, value FROM pivoted) WHERE value != 'NaN' GROUP BY feature) ORDER BY ratio) TO 'noisy_features.parquet';
#+end_src
