"""
Image Quality Evaluation Tool

Automatically evaluates all compression codecs generated by compress_tif.py using GPU-accelerated metrics:
- PSNR (Peak Signal-to-Noise Ratio): Pixel-level accuracy
- SSIM (Structural Similarity Index): Structural similarity
- LPIPS (Learned Perceptual Image Patch Similarity): Perceptual quality

Usage:
    python src/evaluate_quality.py              # Run with default settings
    python src/evaluate_quality.py --no-plots   # Skip visualization generation

The script automatically:
- Uses the same paths as compress_tif.py (data/raw/jump_toy/raw)
- Discovers all .zarr compression codecs in the output directory
- Generates quality comparisons and exports results

Outputs:
1. Terminal table (formatted with rich) showing quality ratings
2. Matplotlib visualizations for first 5 sites
3. CSV exports (detailed per-site and summary statistics)
4. JSON exports (detailed and summary)
"""

import argparse
import json
import warnings
from pathlib import Path
from typing import Dict, List

import numpy as np
import pandas as pd
import torch
import zarr
from lpips import LPIPS
from PIL import Image
from rich.console import Console
from rich.table import Table
from torchmetrics.image import PeakSignalNoiseRatio, StructuralSimilarityIndexMeasure
from tqdm import tqdm
import matplotlib.pyplot as plt

# Suppress torchvision deprecation warnings
warnings.filterwarnings('ignore', category=UserWarning, module='torchvision')

# Register imagecodecs numcodecs for JpegXL and Brotli support
try:
    from imagecodecs.numcodecs import Brotli, Jpegxl
    import numcodecs
    numcodecs.register_codec(Brotli)
    numcodecs.register_codec(Jpegxl)
except (ImportError, AttributeError) as e:
    print(f"Warning: imagecodecs.numcodecs not available: {e}")
    print("JpegXL and Brotli codecs will not be available")


def compute_laplacian_variance(img: np.ndarray) -> float:
    """Variance of Laplacian response across all channels. Higher = sharper.

    Reference: squidpy _sharpness_metrics._laplacian_variance
    """
    from skimage.filters import laplace
    variances = []
    for c in range(img.shape[0]):  # img shape: (C, H, W)
        lap = laplace(img[c].astype(np.float32))
        variances.append(float(np.var(lap)))
    return float(np.mean(variances))


def compute_tenengrad(img: np.ndarray) -> float:
    """Mean Tenengrad energy (sum of squared Sobel gradients) across channels. Higher = sharper.

    Reference: squidpy _sharpness_metrics._tenengrad_mean
    """
    from skimage.filters import sobel_h, sobel_v
    energies = []
    for c in range(img.shape[0]):  # img shape: (C, H, W)
        channel = img[c].astype(np.float32)
        energy = sobel_h(channel) ** 2 + sobel_v(channel) ** 2
        energies.append(float(energy.mean()))
    return float(np.mean(energies))


def setup_device() -> torch.device:
    """Detect GPU availability and return appropriate device."""
    if torch.cuda.is_available():
        device = torch.device("cuda")
        print(f"Using GPU: {torch.cuda.get_device_name(0)}")
        print(f"CUDA version: {torch.version.cuda}")
    else:
        device = torch.device("cpu")
        print("GPU not available, using CPU (this will be slower)")
        print(f"PyTorch version: {torch.__version__}")
        print("Note: Install PyTorch with CUDA support for GPU acceleration:")
        print("  pip install torch torchvision --index-url https://download.pytorch.org/whl/cu121")
    return device


def load_original_images(raw_dir: Path) -> Dict[str, np.ndarray]:
    """
    Load original TIFF images from raw directory and group them by site.

    Returns dict with key=site_name, value=numpy array of shape (nchannels, H, W)
    """
    print(f"Loading original images from {raw_dir}")

    # Group files by site (source__batch__plate__well__site)
    from itertools import groupby

    key_fn = lambda x: (*(x.name.split("__"))[:4], (x.name.split("__"))[5])

    groups = {
        k: list(g)
        for k, g in groupby(sorted(raw_dir.glob("*.tif"), key=key_fn), key=key_fn)
    }

    original_data = {}
    for key, items in tqdm(groups.items(), desc="Loading original images"):
        site_name = "__".join(key)
        nchannels = len(items)

        # Load first image to get shape and dtype
        example_arr = np.array(Image.open(items[0]))
        shape = example_arr.shape
        dtype = example_arr.dtype

        # Create array for all channels
        tmp_arr = np.zeros((nchannels, *shape), dtype=dtype)
        for i, img_path in enumerate(items):
            tmp_arr[i] = np.array(Image.open(img_path))

        original_data[site_name] = tmp_arr

    print(f"Loaded {len(original_data)} image groups")
    return original_data


def load_compressed_images(
    output_dir: Path, codec_name: str, site_names: List[str]
) -> Dict[str, np.ndarray]:
    """
    Load compressed images from Zarr store for a specific codec.

    Returns dict with key=site_name, value=numpy array
    """
    store_path = output_dir / f"{codec_name}.zarr"
    if not store_path.exists():
        raise FileNotFoundError(f"Zarr store not found: {store_path}")

    store = zarr.storage.LocalStore(store_path)
    root = zarr.group(store)

    compressed_data = {}
    for site_name in site_names:
        if site_name in root.keys():
            compressed_data[site_name] = root[site_name][:]
        else:
            print(f"Warning: {site_name} not found in {codec_name}.zarr")

    return compressed_data


def normalize_image_for_metrics(img: np.ndarray) -> torch.Tensor:
    """
    Convert numpy array to PyTorch tensor and normalize to [0, 1] range.

    Args:
        img: numpy array of shape (C, H, W) with dtype uint16 or uint8

    Returns:
        torch tensor of shape (1, C, H, W) with values in [0, 1]
    """
    # Convert to float and normalize based on dtype
    if img.dtype == np.uint16:
        img_float = img.astype(np.float32) / 65535.0
    elif img.dtype == np.uint8:
        img_float = img.astype(np.float32) / 255.0
    else:
        # Assume already in [0, 1]
        img_float = img.astype(np.float32)

    # Convert to tensor and add batch dimension
    tensor = torch.from_numpy(img_float).unsqueeze(0)  # (1, C, H, W)

    return tensor


def compute_metrics(
    original: np.ndarray,
    compressed: np.ndarray,
    device: torch.device = None,
    psnr_metric: PeakSignalNoiseRatio = None,
    ssim_metric: StructuralSimilarityIndexMeasure = None,
    lpips_metric: LPIPS = None,
    sharpness_only: bool = False,
) -> Dict[str, float]:
    """
    Compute PSNR, SSIM, LPIPS, and sharpness metrics for a pair of images.

    Args:
        original: Original image (C, H, W)
        compressed: Compressed image (C, H, W)
        device: torch device (not needed if sharpness_only)
        psnr_metric: Initialized PSNR metric (not needed if sharpness_only)
        ssim_metric: Initialized SSIM metric (not needed if sharpness_only)
        lpips_metric: Initialized LPIPS metric (not needed if sharpness_only)
        sharpness_only: If True, skip PSNR/SSIM/LPIPS and compute only sharpness

    Returns:
        Dict with metric values
    """
    result = {}

    if not sharpness_only:
        # Normalize and move to device
        orig_tensor = normalize_image_for_metrics(original).to(device)
        comp_tensor = normalize_image_for_metrics(compressed).to(device)

        # Compute PSNR
        psnr_value = psnr_metric(comp_tensor, orig_tensor).item()

        # Compute SSIM
        ssim_value = ssim_metric(comp_tensor, orig_tensor).item()

        # LPIPS requires 3-channel images (RGB)
        # For multi-channel microscopy images, we'll compute LPIPS per channel and average
        if orig_tensor.shape[1] == 3:
            # Already 3 channels
            lpips_value = lpips_metric(comp_tensor, orig_tensor).item()
        else:
            # Compute LPIPS per channel
            lpips_values = []
            for c in range(orig_tensor.shape[1]):
                # Repeat channel 3 times to create pseudo-RGB
                orig_rgb = orig_tensor[:, c:c+1, :, :].repeat(1, 3, 1, 1)
                comp_rgb = comp_tensor[:, c:c+1, :, :].repeat(1, 3, 1, 1)
                lpips_values.append(lpips_metric(comp_rgb, orig_rgb).item())
            lpips_value = np.mean(lpips_values)

        result.update({
            'psnr': psnr_value,
            'ssim': ssim_value,
            'lpips': lpips_value,
        })

    # Sharpness metrics (computed on CPU numpy arrays)
    orig_lap = compute_laplacian_variance(original)
    comp_lap = compute_laplacian_variance(compressed)
    orig_ten = compute_tenengrad(original)
    comp_ten = compute_tenengrad(compressed)

    result.update({
        'laplacian_orig': orig_lap,
        'laplacian_comp': comp_lap,
        'laplacian_ratio': comp_lap / orig_lap if orig_lap > 0 else float('nan'),
        'laplacian_diff': orig_lap - comp_lap,
        'tenengrad_orig': orig_ten,
        'tenengrad_comp': comp_ten,
        'tenengrad_ratio': comp_ten / orig_ten if orig_ten > 0 else float('nan'),
        'tenengrad_diff': orig_ten - comp_ten,
    })

    return result


def evaluate_all_codecs(
    original_data: Dict[str, np.ndarray],
    output_dir: Path,
    device: torch.device = None,
    sharpness_only: bool = False,
) -> pd.DataFrame:
    """
    Evaluate all compression codecs against original images.

    Returns DataFrame with columns: site_name, codec, and metric columns.
    If sharpness_only, only sharpness metrics are computed (no GPU needed).
    """
    # Find all codec zarr directories
    codec_dirs = [d for d in output_dir.glob("*.zarr") if d.is_dir()]
    codec_names = [d.stem for d in codec_dirs]

    if not codec_names:
        raise ValueError(f"No .zarr directories found in {output_dir}")

    print(f"Found {len(codec_names)} codecs to evaluate: {codec_names}")

    # Initialize metrics on device (skip if sharpness_only)
    psnr_metric = None
    ssim_metric = None
    lpips_metric = None
    if not sharpness_only:
        # data_range=1.0 since we normalize images to [0, 1]
        psnr_metric = PeakSignalNoiseRatio(data_range=1.0).to(device)
        ssim_metric = StructuralSimilarityIndexMeasure(data_range=1.0).to(device)
        # Using VGG for better perceptual accuracy. Options: 'alex' (fast), 'vgg' (more accurate), 'squeeze' (fastest)
        lpips_metric = LPIPS(net='vgg').to(device)

    # Collect results
    results = []

    site_names = list(original_data.keys())

    desc = "Computing sharpness" if sharpness_only else "Evaluating codecs"
    for codec_name in tqdm(codec_names, desc=desc):
        try:
            compressed_data = load_compressed_images(output_dir, codec_name, site_names)

            for site_name in tqdm(site_names, desc=f"  {codec_name}", leave=False):
                if site_name not in compressed_data:
                    continue

                original = original_data[site_name]
                compressed = compressed_data[site_name]

                # Compute metrics
                metrics = compute_metrics(
                    original, compressed, device,
                    psnr_metric, ssim_metric, lpips_metric,
                    sharpness_only=sharpness_only,
                )

                results.append({
                    'site_name': site_name,
                    'codec': codec_name,
                    **metrics,
                })

        except Exception as e:
            print(f"Error evaluating {codec_name}: {e}")
            continue

    df = pd.DataFrame(results)
    return df


def print_comparison_table(df: pd.DataFrame, sharpness_only: bool = False):
    """Print a formatted comparison table to the terminal using rich."""
    console = Console()

    sharpness_cols = [
        'laplacian_orig', 'laplacian_comp', 'laplacian_ratio', 'laplacian_diff',
        'tenengrad_orig', 'tenengrad_comp', 'tenengrad_ratio', 'tenengrad_diff',
    ]

    if sharpness_only:
        # Sharpness-only table
        avg_metrics = df.groupby('codec')[sharpness_cols].mean()
        avg_metrics = avg_metrics.sort_values('laplacian_ratio', ascending=False)

        table = Table(title="Sharpness Metrics Comparison", show_header=True, header_style="bold magenta")
        table.add_column("Codec", style="cyan", no_wrap=True)
        table.add_column("Lap. Orig", justify="right", style="green")
        table.add_column("Lap. Comp", justify="right", style="green")
        table.add_column("Lap. Ratio", justify="right", style="green")
        table.add_column("Lap. Diff", justify="right", style="green")
        table.add_column("Ten. Orig", justify="right", style="green")
        table.add_column("Ten. Comp", justify="right", style="green")
        table.add_column("Ten. Ratio", justify="right", style="green")
        table.add_column("Ten. Diff", justify="right", style="green")

        for codec, row in avg_metrics.iterrows():
            table.add_row(
                codec,
                f"{row['laplacian_orig']:.4f}",
                f"{row['laplacian_comp']:.4f}",
                f"{row['laplacian_ratio']:.4f}",
                f"{row['laplacian_diff']:.4f}",
                f"{row['tenengrad_orig']:.4f}",
                f"{row['tenengrad_comp']:.4f}",
                f"{row['tenengrad_ratio']:.4f}",
                f"{row['tenengrad_diff']:.4f}",
            )
    else:
        # Full table with all metrics
        metric_cols = ['psnr', 'ssim', 'lpips'] + sharpness_cols
        avg_metrics = df.groupby('codec')[metric_cols].mean()
        avg_metrics = avg_metrics.sort_values('ssim', ascending=False)

        table = Table(title="Compression Quality Comparison", show_header=True, header_style="bold magenta")

        table.add_column("Codec", style="cyan", no_wrap=True)
        table.add_column("PSNR (dB)", justify="right", style="green")
        table.add_column("SSIM", justify="right", style="green")
        table.add_column("LPIPS", justify="right", style="green")
        table.add_column("Lap. Orig", justify="right", style="green")
        table.add_column("Lap. Comp", justify="right", style="green")
        table.add_column("Lap. Ratio", justify="right", style="green")
        table.add_column("Lap. Diff", justify="right", style="green")
        table.add_column("Ten. Orig", justify="right", style="green")
        table.add_column("Ten. Comp", justify="right", style="green")
        table.add_column("Ten. Ratio", justify="right", style="green")
        table.add_column("Ten. Diff", justify="right", style="green")
        table.add_column("Quality", justify="center")

        for codec, row in avg_metrics.iterrows():
            psnr = row['psnr']
            ssim = row['ssim']
            lpips = row['lpips']

            # Determine overall quality
            if ssim >= 0.95 and lpips <= 0.05:
                quality = "[bold green]Excellent[/bold green]"
            elif ssim >= 0.90 and lpips <= 0.10:
                quality = "[green]Good[/green]"
            elif ssim >= 0.80 and lpips <= 0.20:
                quality = "[yellow]Fair[/yellow]"
            else:
                quality = "[red]Poor[/red]"

            table.add_row(
                codec,
                f"{psnr:.2f}",
                f"{ssim:.4f}",
                f"{lpips:.4f}",
                f"{row['laplacian_orig']:.4f}",
                f"{row['laplacian_comp']:.4f}",
                f"{row['laplacian_ratio']:.4f}",
                f"{row['laplacian_diff']:.4f}",
                f"{row['tenengrad_orig']:.4f}",
                f"{row['tenengrad_comp']:.4f}",
                f"{row['tenengrad_ratio']:.4f}",
                f"{row['tenengrad_diff']:.4f}",
                quality,
            )

    console.print(table)

    # Print interpretation guide
    console.print("\n[bold]Metric Interpretation:[/bold]")
    if not sharpness_only:
        console.print("  PSNR: Pixel accuracy. Higher = better. 30+ good, 35+ excellent.")
        console.print("  SSIM: Structural similarity (0-1). Higher = better. 0.9+ good.")
        console.print("  LPIPS: Perceptual quality. Lower = better. <0.1 good.")
    console.print("  Laplacian Ratio: Sharpness preservation (compressed/original). Closer to 1.0 = better.")
    console.print("  Tenengrad Ratio: Edge energy preservation (compressed/original). Closer to 1.0 = better.")


def generate_visualizations(
    df: pd.DataFrame,
    original_data: Dict[str, np.ndarray],
    output_dir: Path,
    results_dir: Path,
):
    """
    Generate matplotlib visualizations comparing codecs.

    Creates one plot per site showing: original, compressed (all codecs), metrics
    """
    results_dir.mkdir(parents=True, exist_ok=True)

    codecs = df['codec'].unique()
    sites = df['site_name'].unique()

    print(f"Generating visualizations for {len(sites)} sites...")

    # Generate one comparison plot per site (limit to first few sites to avoid too many plots)
    for site_name in tqdm(sites[:5], desc="Creating plots"):  # Limit to 5 sites
        site_df = df[df['site_name'] == site_name]

        if site_name not in original_data:
            continue

        original = original_data[site_name]
        nchannels = original.shape[0]

        # Create subplots: rows = codecs + 1 (for original), cols = channels
        fig, axes = plt.subplots(
            nrows=len(codecs) + 1,
            ncols=nchannels,
            figsize=(nchannels * 4, (len(codecs) + 1) * 3)
        )

        # Ensure axes is 2D
        if nchannels == 1:
            axes = axes.reshape(-1, 1)

        # Plot original
        for ch in range(nchannels):
            axes[0, ch].imshow(original[ch], cmap='gray')
            axes[0, ch].set_title(f"Original - Channel {ch}")
            axes[0, ch].axis('off')

        # Plot compressed versions
        for i, codec in enumerate(codecs):
            codec_df = site_df[site_df['codec'] == codec]
            if len(codec_df) == 0:
                continue

            metrics = codec_df.iloc[0]

            # Load compressed image
            try:
                store_path = output_dir / f"{codec}.zarr"
                store = zarr.storage.LocalStore(store_path)
                root = zarr.group(store)
                compressed = root[site_name][:]

                for ch in range(nchannels):
                    axes[i + 1, ch].imshow(compressed[ch], cmap='gray')
                    title = f"{codec}\nPSNR:{metrics['psnr']:.1f} SSIM:{metrics['ssim']:.3f} LPIPS:{metrics['lpips']:.3f}"
                    title += f"\nLap:{metrics['laplacian_ratio']:.3f} Ten:{metrics['tenengrad_ratio']:.3f}"
                    axes[i + 1, ch].set_title(title, fontsize=8)
                    axes[i + 1, ch].axis('off')

            except Exception as e:
                print(f"Error loading {codec} for {site_name}: {e}")
                continue

        plt.tight_layout()
        plot_path = results_dir / f"comparison_{site_name}.png"
        plt.savefig(plot_path, dpi=150, bbox_inches='tight')
        plt.close()

    print(f"Visualizations saved to {results_dir}")


def save_results(df: pd.DataFrame, results_dir: Path, sharpness_only: bool = False):
    """Save results to CSV and JSON formats."""
    results_dir.mkdir(parents=True, exist_ok=True)

    if sharpness_only:
        # In sharpness-only mode, try to merge into existing detailed CSV
        csv_path = results_dir / "metrics_detailed.csv"
        if csv_path.exists():
            existing_df = pd.read_csv(csv_path)
            sharpness_cols = [
                'laplacian_orig', 'laplacian_comp', 'laplacian_ratio', 'laplacian_diff',
                'tenengrad_orig', 'tenengrad_comp', 'tenengrad_ratio', 'tenengrad_diff',
            ]
            # Drop old sharpness columns if they exist
            existing_df = existing_df.drop(
                columns=[c for c in sharpness_cols if c in existing_df.columns],
                errors='ignore',
            )
            merged = existing_df.merge(
                df[['site_name', 'codec'] + sharpness_cols],
                on=['site_name', 'codec'],
                how='left',
            )
            merged.to_csv(csv_path, index=False)
            print(f"Merged sharpness metrics into {csv_path}")
            df = merged  # Use merged for summary
        else:
            csv_path = results_dir / "sharpness_detailed.csv"
            df.to_csv(csv_path, index=False)
            print(f"Sharpness results saved to {csv_path}")
    else:
        # Save detailed results
        csv_path = results_dir / "metrics_detailed.csv"
        df.to_csv(csv_path, index=False)
        print(f"Detailed results saved to {csv_path}")

    # Determine which metric columns are present for summary
    metric_cols = [c for c in [
        'psnr', 'ssim', 'lpips',
        'laplacian_orig', 'laplacian_comp', 'laplacian_ratio', 'laplacian_diff',
        'tenengrad_orig', 'tenengrad_comp', 'tenengrad_ratio', 'tenengrad_diff',
    ] if c in df.columns]

    # Save summary statistics
    summary = df.groupby('codec')[metric_cols].agg(['mean', 'std', 'min', 'max'])
    summary_csv = results_dir / "metrics_summary.csv"
    summary.to_csv(summary_csv)
    print(f"Summary statistics saved to {summary_csv}")

    # Save as JSON
    json_path = results_dir / "metrics_detailed.json"
    df.to_json(json_path, orient='records', indent=2)

    # Create summary JSON
    summary_dict = {}
    for codec in df['codec'].unique():
        codec_df = df[df['codec'] == codec]
        summary_dict[codec] = {}
        for col in metric_cols:
            summary_dict[codec][col] = {
                'mean': float(codec_df[col].mean()),
                'std': float(codec_df[col].std()),
                'min': float(codec_df[col].min()),
                'max': float(codec_df[col].max()),
            }

    summary_json = results_dir / "metrics_summary.json"
    with open(summary_json, 'w') as f:
        json.dump(summary_dict, f, indent=2)

    print(f"JSON results saved to {json_path} and {summary_json}")


def main():
    parser = argparse.ArgumentParser(
        description="Evaluate image compression quality using PSNR, SSIM, LPIPS, and sharpness metrics"
    )
    parser.add_argument(
        "--no-plots",
        action="store_true",
        help="Skip generating matplotlib visualizations",
    )
    parser.add_argument(
        "--sharpness-only",
        action="store_true",
        help="Only compute Laplacian variance and Tenengrad sharpness metrics (no GPU needed)",
    )

    args = parser.parse_args()

    # Use the same paths as compress_tif.py
    #input_dir = Path("data/raw/jump_toy_compress/raw")
    input_dir = Path("data/raw/jump_target2_subset_BR00121438/raw")

    output_dir = input_dir.parent
    results_dir = output_dir / "results"

    print(f"Input directory (raw images): {input_dir}")
    print(f"Output directory (compressed .zarr): {output_dir}")
    print(f"Results directory: {results_dir}")

    # Automatically discover all compression codecs
    codec_dirs = sorted([d for d in output_dir.glob("*.zarr") if d.is_dir()])
    if codec_dirs:
        codec_names = [d.stem for d in codec_dirs]
        print(f"\nFound {len(codec_names)} compression codecs:")
        for codec in codec_names:
            print(f"  - {codec}")
    else:
        print(f"\nWarning: No .zarr directories found in {output_dir}")
        print("Please run compress_tif.py first to generate compressed images.")
        return

    # Setup device (skip GPU for sharpness-only mode)
    device = None
    if not args.sharpness_only:
        device = setup_device()
    else:
        print("\nSharpness-only mode: skipping GPU setup and PSNR/SSIM/LPIPS")

    # Load original images
    print()
    original_data = load_original_images(input_dir)

    if not original_data:
        print("No original images found!")
        return

    # Evaluate all codecs
    mode_desc = "sharpness" if args.sharpness_only else "compression quality"
    print(f"\nEvaluating {mode_desc}...")
    df = evaluate_all_codecs(
        original_data, output_dir, device,
        sharpness_only=args.sharpness_only,
    )

    if df.empty:
        print("No results to display!")
        return

    # Display results
    print("\n" + "="*80)
    print_comparison_table(df, sharpness_only=args.sharpness_only)
    print("="*80 + "\n")

    # Save results
    save_results(df, results_dir, sharpness_only=args.sharpness_only)

    # Generate visualizations (skip in sharpness-only mode)
    if not args.no_plots and not args.sharpness_only:
        generate_visualizations(df, original_data, output_dir, results_dir)

    print(f"\nEvaluation complete! Results saved to {results_dir}/")


if __name__ == "__main__":
    main()
