#+TITLE: Analyses
#+PROPERTY: header-args:duckdb :session ddb :results output

Summary of analyses to get and process profiles
* Create an index of images to download
:PROPERTIES:
:header-args:sql: :tangle ./generate_jump_lite_index.sql
:END:
** Get red-listed and gray-listed plates
# :PROPERTIES:
# :header-args:sq: :session ddb:exports both :results output
# :END:

*** Redlisted plates

=redlist.csv= These are based off [[https://github.com/broadinstitute/jump-profiling-recipe/blob/d2512d978ca17aafead0e99de66386337e6312e4/src/jump_profiling_recipe/preprocessing/metadata.py#L278https://github.com/broadinstitute/jump-profiling-recipe/blob/d2512d978ca17aafead0e99de66386337e6312e4/src/jump_profiling_recipe/preprocessing/metadata.py#L278][this]] link. Plates that should NEVER be on the analysis. In the case of =source_15= they are missing loaddata_csv.
#+begin_src sql :session ddb :tangle generate_jl_index.sql 
  .maxwidth 80
  .maxrows 4
  .cd /work/datasets/jump_lite/misc/
  INSTALL httpfs;
  LOAD httpfs;
  CREATE OR REPLACE TABLE redlist AS (SELECT COLUMNS('^Metadata_(Source|Batch|Plate)$') FROM read_csv('https://github.com/jump-cellpainting/datasets/raw/refs/heads/main/metadata/plate.csv.gz') WHERE
  ((Metadata_Source = 'source_4' AND suffix(Metadata_Batch, 'Batch12')) OR
  (Metadata_Source = 'source_3' AND (regexp_matches(Metadata_Batch, '^CP_3[23456]_all_Phenix1$') OR Metadata_Batch in ['CP59', 'CP60'])) OR
  ((Metadata_Source = 'source_15') AND Metadata_Plate in ['PEP00004458', 'PEP00004421'])));
  COPY redlist TO 'redlist.csv';
  FROM redlist;
#+end_src

#+RESULTS:
#+begin_example
D ┌─────────────────┬────────────────────┬────────────────┐
│ Metadata_Source │   Metadata_Batch   │ Metadata_Plate │
│     varchar     │      varchar       │    varchar     │
├─────────────────┼────────────────────┼────────────────┤
│ source_15       │ 2022_02_28_Batch1  │ PEP00004458    │
│ source_15       │ 2022_03_23_Batch1  │ PEP00004421    │
│    ·            │         ·          │     ·          │
│    ·            │         ·          │     ·          │
│    ·            │         ·          │     ·          │
│ source_4        │ 2021_08_23_Batch12 │ BR00126717     │
│ source_4        │ 2021_08_23_Batch12 │ BR00126718     │
├─────────────────┴────────────────────┴────────────────┤
│ 169 rows (4 shown)                          3 columns │
└───────────────────────────────────────────────────────┘
#+end_example

*** Negcon-only plate
=graylist.csv= These plates contain are full of negative controls.
#+begin_src duckdb :session ddb :tangle generate_jl_index.sql 
  CREATE OR REPLACE TABLE graylist AS (SELECT COLUMNS('^Metadata_(Source|Batch|Plate)$') FROM read_csv('https://github.com/jump-cellpainting/datasets/raw/refs/heads/main/metadata/plate.csv.gz') WHERE regexp_matches(Metadata_Plate, 'CP-CC9-R[123456]-28'));
  COPY graylist TO 'graylist.csv';
  FROM graylist;
#+end_src

#+RESULTS:
#+begin_results
┌─────────────────┬────────────────┬────────────────┐
│ Metadata_Source │ Metadata_Batch │ Metadata_Plate │
│     varchar     │    varchar     │    varchar     │
├─────────────────┼────────────────┼────────────────┤
│ source_13       │ 20220914_Run1  │ CP-CC9-R1-28   │
│ source_13       │ 20221009_Run2  │ CP-CC9-R2-28   │
│ source_13       │ 20221017_Run3  │ CP-CC9-R3-28   │
│ source_13       │ 20221024_Run4  │ CP-CC9-R4-28   │
│ source_13       │ 20221109_Run5  │ CP-CC9-R5-28   │
│ source_13       │ 20221120_Run6  │ CP-CC9-R6-28   │
└─────────────────┴────────────────┴────────────────┘
#+end_results

** Generate JUMP index
Use the redlist and graylist to generate the JUMPindex
#+begin_src duckdb :session ddb :tangle generate_jl_index.sql 
  CREATE OR REPLACE TABLE jump_plates AS (SELECT COLUMNS('^Metadata_(Source|Batch|Plate)$') FROM read_csv('https://github.com/jump-cellpainting/datasets/raw/refs/heads/main/metadata/plate.csv.gz') ANTI JOIN (FROM 'graylist.csv' UNION ALL FROM 'redlist.csv') using(Metadata_Source,Metadata_Batch,Metadata_Plate));
  FROM jump_plates;
#+end_src

#+RESULTS:
#+begin_results
┌─────────────────┬─────────────────┬────────────────┐
│ Metadata_Source │ Metadata_Batch  │ Metadata_Plate │
│     varchar     │     varchar     │    varchar     │
├─────────────────┼─────────────────┼────────────────┤
│ source_1        │ Batch1_20221004 │ UL000109       │
│ source_1        │ Batch1_20221004 │ UL001641       │
│    ·            │       ·         │    ·           │
│    ·            │       ·         │    ·           │
│    ·            │       ·         │    ·           │
│ source_9        │ 20211103-Run16  │ GR00004420     │
│ source_9        │ 20211103-Run16  │ GR00004421     │
├─────────────────┴─────────────────┴────────────────┤
│ 2350 rows (4 shown)                      3 columns │
└────────────────────────────────────────────────────┘
#+end_results

*** Per-plate index of JUMP
#+begin_src duckdb :session ddb :tangle generate_jl_index.sql 
  .maxwidth 80
  CREATE OR REPLACE TABLE loaddata_uris AS (SELECT *, format('s3://cellpainting-gallery/cpg0016-jump/{}/workspace/load_data_csv/{}/{}/load_data_with_illum.csv', Metadata_Source, Metadata_Batch, Metadata_Plate) AS uri FROM jump_plates);
  FROM loaddata_uris;
  SET VARIABLE csv_files = (SELECT list(uri) FROM loaddata_uris);
#+end_src

#+RESULTS:
#+begin_results
┌─────────────────┬─────────────────┬────────────────┬─────────────────────────┐
│ Metadata_Source │ Metadata_Batch  │ Metadata_Plate │           uri           │
│     varchar     │     varchar     │    varchar     │         varchar         │
├─────────────────┼─────────────────┼────────────────┼─────────────────────────┤
│ source_1        │ Batch1_20221004 │ UL000109       │ s3://cellpainting-gal…  │
│ source_1        │ Batch1_20221004 │ UL001641       │ s3://cellpainting-gal…  │
│    ·            │       ·         │    ·           │            ·            │
│    ·            │       ·         │    ·           │            ·            │
│    ·            │       ·         │    ·           │            ·            │
│ source_9        │ 20211103-Run16  │ GR00004420     │ s3://cellpainting-gal…  │
│ source_9        │ 20211103-Run16  │ GR00004421     │ s3://cellpainting-gal…  │
├─────────────────┴─────────────────┴────────────────┴─────────────────────────┤
│ 2350 rows (4 shown)                                                4 columns │
└──────────────────────────────────────────────────────────────────────────────┘
#+end_results

*** Create per-site index
#+begin_src sql :session ddb :tangle generate_jl_index.sql 
  CREATE OR REPLACE TABLE jump_index AS (SELECT COLUMNS('^Metadata_(Source|Batch|Plate|Well|Site)$'),COLUMNS('URL_Orig(DNA|Mito|AGP|ER|RNA)')  FROM read_csv(getVariable('csv_files'), union_by_name=True));
  COPY jump_index TO 'jump_index.parquet';
  FROM jump_index;
#+end_src

#+RESULTS:
#+begin_example
┌─────────────────┬─────────────────┬───┬──────────────────────┐
│ Metadata_Source │ Metadata_Batch  │ … │     URL_OrigAGP      │
│     varchar     │     varchar     │   │       varchar        │
├─────────────────┼─────────────────┼───┼──────────────────────┤
│ source_1        │ Batch1_20221004 │ … │ s3://cellpainting-…  │
│ source_1        │ Batch1_20221004 │ … │ s3://cellpainting-…  │
│    ·            │       ·         │ · │          ·           │
│    ·            │       ·         │ · │          ·           │
│    ·            │       ·         │ · │          ·           │
│ source_9        │ 20211103-Run16  │ … │ s3://cellpainting-…  │
│ source_9        │ 20211103-Run16  │ … │ s3://cellpainting-…  │
├─────────────────┴─────────────────┴───┴──────────────────────┤
│ 8022106 rows                            10 columns (3 shown) │
│ 8.02 million rows                                    4 shown │
└──────────────────────────────────────────────────────────────┘
#+end_example

*** Save a "tidy" version of the JUMP index, with one image per row
#+begin_src sql  :session ddb :tangle generate_jl_index.sql 
  CREATE OR REPLACE TABLE jump_index_tidy AS (
  UNPIVOT jump_index ON COLUMNS('URL_*') INTO NAME Metadata_Channel VALUE uri);
  COPY jump_index_tidy TO 'jump_index_tidy.parquet';
  FROM jump_index_tidy;
#+end_src

#+RESULTS:
#+begin_example
┌─────────────────┬───┬──────────────────┬──────────────────────┐
│ Metadata_Source │ … │ Metadata_Channel │         uri          │
│     varchar     │   │     varchar      │       varchar        │
├─────────────────┼───┼──────────────────┼──────────────────────┤
│ source_1        │ … │ URL_OrigRNA      │ s3://cellpainting-…  │
│ source_1        │ … │ URL_OrigMito     │ s3://cellpainting-…  │
│    ·            │ · │      ·           │          ·           │
│    ·            │ · │      ·           │          ·           │
│    ·            │ · │      ·           │          ·           │
│ source_9        │ … │ URL_OrigDNA      │ s3://cellpainting-…  │
│ source_9        │ … │ URL_OrigAGP      │ s3://cellpainting-…  │
├─────────────────┴───┴──────────────────┴──────────────────────┤
│ 39612107 rows                             7 columns (3 shown) │
│ 39.61 million rows                                    4 shown │
└───────────────────────────────────────────────────────────────┘
#+end_example


** Create a JUMP-Lite index
*** Filter plates relevant to JUMP-lite
#+begin_src sql :session ddb :tangle generate_jl_index.sql 
  CREATE OR REPLACE TABLE jl_index AS (FROM jump_index JOIN (SELECT #2 AS Metadata_Plate FROM read_csv('https://zenodo.org/api/records/18705140/files/jl_plates.csv/content')) using(Metadata_Plate));
  COPY jl_index TO 'jl_index.parquet';
  FROM jl_index;
#+end_src

#+RESULTS:
#+begin_example
┌─────────────────┬───────────────────┬───┬──────────────────────┐
│ Metadata_Source │  Metadata_Batch   │ … │     URL_OrigAGP      │
│     varchar     │      varchar      │   │       varchar        │
├─────────────────┼───────────────────┼───┼──────────────────────┤
│ source_2        │ 20211003_Batch_13 │ … │ s3://cellpainting-…  │
│ source_2        │ 20211003_Batch_13 │ … │ s3://cellpainting-…  │
│    ·            │       ·           │ · │          ·           │
│    ·            │       ·           │ · │          ·           │
│    ·            │       ·           │ · │          ·           │
│ source_13       │ 20221009_Run2     │ … │ s3://cellpainting-…  │
│ source_13       │ 20221009_Run2     │ … │ s3://cellpainting-…  │
├─────────────────┴───────────────────┴───┴──────────────────────┤
│ 1887910 rows (1.89 million rows, 4 shown) 10 columns (3 shown) │
└────────────────────────────────────────────────────────────────┘
#+end_example

*** Tidy version
#+begin_src sql :session ddb :tangle generate_jl_index.sql 
  CREATE OR REPLACE TABLE jl_index_tidy AS (
  UNPIVOT jl_index ON COLUMNS('URL_*') INTO NAME Metadata_Channel VALUE uri);
  COPY jl_index_tidy TO 'jl_index_tidy.parquet';
  FROM jl_index_tidy;
#+end_src

#+RESULTS:
#+begin_example
┌─────────────────┬───┬──────────────────┬──────────────────────┐
│ Metadata_Source │ … │ Metadata_Channel │         uri          │
│     varchar     │   │     varchar      │       varchar        │
├─────────────────┼───┼──────────────────┼──────────────────────┤
│ source_2        │ … │ URL_OrigRNA      │ s3://cellpainting-…  │
│ source_2        │ … │ URL_OrigMito     │ s3://cellpainting-…  │
│    ·            │ · │      ·           │          ·           │
│    ·            │ · │      ·           │          ·           │
│    ·            │ · │      ·           │          ·           │
│ source_13       │ … │ URL_OrigDNA      │ s3://cellpainting-…  │
│ source_13       │ … │ URL_OrigAGP      │ s3://cellpainting-…  │
├─────────────────┴───┴──────────────────┴──────────────────────┤
│ 9439550 rows (9.44 million rows, 4 shown) 7 columns (3 shown) │
└───────────────────────────────────────────────────────────────┘
#+end_example

** Sample sites
To lower the number of sites needed we sample four sites per unique wells. Note that we include all wells of the JUMP-lite plates. We could select specific plates using =/work/datasets/jump_lite/misc/metadata_dataset_filtered_4reps.parquet=.
#+begin_src sql :session ddb :tangle generate_jl_index.sql 
  CREATE OR REPLACE TABLE jl_index_sampled AS ( SELECT * EXCLUDE rn FROM (SELECT *, row_number() OVER (PARTITION BY Metadata_Plate,Metadata_Well) as rn FROM jl_index) WHERE rn < 5);
  COPY jl_index_sampled TO 'jl_index_sampled.parquet';
  FROM jl_index_sampled;
#+end_src

#+RESULTS:
#+begin_example
┌─────────────────┬──────────────────────┬───┬──────────────────────┐
│ Metadata_Source │    Metadata_Batch    │ … │     URL_OrigAGP      │
│     varchar     │       varchar        │   │       varchar        │
├─────────────────┼──────────────────────┼───┼──────────────────────┤
│ source_4        │ 2021_05_10_Batch3    │ … │ s3://cellpainting-…  │
│ source_4        │ 2021_05_10_Batch3    │ … │ s3://cellpainting-…  │
│    ·            │         ·            │ · │          ·           │
│    ·            │         ·            │ · │          ·           │
│    ·            │         ·            │ · │          ·           │
│ source_6        │ p211004CPU2OS48hw3…  │ … │ s3://cellpainting-…  │
│ source_6        │ p211004CPU2OS48hw3…  │ … │ s3://cellpainting-…  │
├─────────────────┴──────────────────────┴───┴──────────────────────┤
│ 855519 rows (4 shown)                        10 columns (3 shown) │
└───────────────────────────────────────────────────────────────────┘
#+end_example

*** Tidy
#+begin_src sql :session ddb :tangle generate_jl_index.sql 
  CREATE OR REPLACE TABLE jl_index_sampled_tidy AS (
  UNPIVOT jl_index_sampled On COLUMNS('URL_*') INTO NAME Metadata_Channel VALUE uri);
  COPY jl_index_sampled_tidy TO 'jl_index_sampled_tidy.parquet';
  FROM jl_index_sampled_tidy;
#+end_src

#+RESULTS:
#+begin_example
┌─────────────────┬───┬──────────────────┬──────────────────────┐
│ Metadata_Source │ … │ Metadata_Channel │         uri          │
│     varchar     │   │     varchar      │       varchar        │
├─────────────────┼───┼──────────────────┼──────────────────────┤
│ source_4        │ … │ URL_OrigRNA      │ s3://cellpainting-…  │
│ source_4        │ … │ URL_OrigMito     │ s3://cellpainting-…  │
│    ·            │ · │      ·           │          ·           │
│    ·            │ · │      ·           │          ·           │
│    ·            │ · │      ·           │          ·           │
│ source_6        │ … │ URL_OrigDNA      │ s3://cellpainting-…  │
│ source_6        │ … │ URL_OrigAGP      │ s3://cellpainting-…  │
├─────────────────┴───┴──────────────────┴──────────────────────┤
│ 4277595 rows (4.28 million rows, 4 shown) 7 columns (3 shown) │
└───────────────────────────────────────────────────────────────┘
#+end_example

* Create JUMP index
** Download data
#+begin_src sh
  python download_images.py
#+end_src

** Compress data
First download and compress data
#+begin_src
  python ../src/compress_tif.py
#+end_src

** Run aliby featurizarion analysis
Then use this data to produce profiles. Remember to uncomment all models in =model_setup_params=. Also watch out that the number of devices fit into memory and that number in =featurize.sh= matches the one in  =aliby_featurize.py=.
#+begin_src
  bash deploy_nahual_featurizers.sh # Deploy servers
  python aliby_featurize.py
#+end_src

*** In rare cases, error may happen
Use this one-liner to remove files that are too small
#+begin_src sh
  find /work/datasets/aliby_output/dinov2_random/jump_core_annotated/jpegxl_lossy_mq.zarr/ -type f -size -5k -printf "%p %s\n"
#+end_src

** Aggregate data to have per-well
#+begin_src fish
  for i in /work/datasets/aliby_output/*/jump_core_annotated;
  echo "Running $i"
  bash get_perwell.sh $i/jpegxl_lossy_mq.zarr/profiles $i/perwell.parquet;
  end
#+end_src

** Correct the data
(Johan's branch)

** Run statistical analyses and plot
(Johan's branch)
